### ISSUE TITLE
Question about the Exercise 1.3: Compute the air resistance on a football -- Fu

### ISSUE THREAD

**Issue by acse-20449ecc** [ese-msc/introduction-to-python#10]
Conclusion

There seems to be a small mistake with the stem of exercise 1.3, the formula of the cross-sectional area A should be pi * ball_radius^2 rather than pi * ball_radius. 

Procedure

Given 𝐹𝑑=1/2 * 𝐶_𝐷 * 𝜌 * 𝐴 * 𝑣^2, and 𝜌 is the density of the air, which is 1.2 kg/m^3,
𝑣 is the velocity of the object, which is 50.8 m/s,
𝐴 is the cross-sectional area (perpendicular to the velocity direction), according to given information, which is pi * ball_radius = pi * 0.11 m, and 𝐶𝐷 is the drag coefficient, which is 0.2

To compute the drag force, the equation will therefore be 
Fd = 0.5 * 0.2 * 1.2 * pi * 0.11 * 50.8 * 50.8

The outcome of my code is 107.0 N, which is wrong according to pybryt
Hence I double checked my code and also calculated by myself, taking pi as 3.14159, I got Fd = 107.01652919232, which suggests that if the given formulations are all correct, this should be the expected answer.
So I checked the units, noticed that for the given formulation, the unit of the final answer should be kg/s^2, which doesn't match 1 N = 1 kg * m/s^2
Therefore, I assume that the cross-sectional area A should actually be pi * ball_radius^2 (make more sense in both units and area calculation), edited "A = pi * ball_radius" to "A = pi * ball_radius ** 2", got 11.8 newton, the expected outcome of pybryt.

**Comment by marijanbeg** [comment]
Hi @acse-20449ecc, thank you for your question.

You are right :) We intentionally made that mistake and asked you to "Complete **and correct** the following code that computes the drag force." If you did not correct the cross-sectional area `A`, PyBryt should have warned you. Did you get an error message from PyBryt?

**Comment by marijanbeg** [comment]
Addressed by making "and correct" bold in the exercise to emphasise the requirement and avoid confusion.

**Comment by acse-20449ecc** [comment]
Thank you very much for your reply
I downloaded the code to my laptop to do the exercise, and met some problem while using jupyter notebook about the dead kernel. Though I managed to fix it after several hours' struggling, sadly, my PyBryt actually does not work properly, and I did not concern much about it since I can still check the answer with okpy.
I've just tried to run the exercise code with JupyterHub, everything works fine and I saw the expected error message, guess there is still something wrong in my jupyter notebook installation. I will now check my code again using JupyterHub so that I won't miss messages, thank you for letting me know about it :)

**Comment by marijanbeg** [comment]
Thank you, @acse-20449ecc, for clarification. We would be very interested in learning more about the installation issues you encountered. We would be grateful if you could raise another issue so that we can try to help you, and make any required improvements or fixes to our course. :)

Thank you very much for your valuable feedback, and please do not hesitate to raise further issues.
