### ISSUE TITLE
Question about exercise 3.9

### ISSUE THREAD

**Issue by acse-e9c6b196** [ese-msc/introduction-to-python#16]
Hi,

I have a question regarding the "compute_velocity" function in exercise 3.9. 

If I understand correctly in the brackets of the Trapezoidal rule it is a[0]/2+a[k]/2+sum(a[**1**:k]). However, when I use that in the code and check the calculation it shows as incorrect final solution (both acc_array  and time_array are confirmed to be correct).

On the other hand if I use a[0]/2+a[k]/2+sum(a[**0**:k] the test confirms that function is calculated correctly, but in this case isn't a[0] double counted, since sum() will start from a[0]?

Thank you

**Comment by marijanbeg** [comment]
Hi @acse-e9c6b196, thank you very much for raising this issue. We will investigate this and get back to you as soon as possible.

Thank you for your patience.

**Comment by marijanbeg** [comment]
Of course, you can find my email on this webpage: https://www.imperial.ac.uk/people/m.beg

**Comment by marijanbeg** [comment]
Hi @acse-e9c6b196, thank you for your patience. We investigated this question, and we agree with you. This is a mistake in our tests because we assumed finite-difference-like discretisation instead of finite-element-like.

The tests are now modified and will be released soon.
