### ISSUE TITLE
Exercise 1.5

### ISSUE THREAD

**Issue by edsml-na506** [ese-msc/introduction-to-python#17]
For the exponent portion of the equation,
I attempted to import the function 'exp' 
But how do I make it work? I get the error below.
Manually evaluating this expression I get: 0.176033.

![image](https://user-images.githubusercontent.com/88665260/131642119-3b183cbb-2365-47ae-a041-e27bb408e2e0.png)

**Comment by marijanbeg** [comment]
Hi @edsml-na506, thank you for your question.

When you import functions/variables/classes using `from math import pi, sqrt, e, exp`, then you refer to them as `e`, `exp`,... and not as `math.exp` in your code. For instance, in your code, you call `sqrt` which is correct. However, in the same line, you call `math.exp` which is wrong - it should be only `exp`.

On the other hand, if you imported `math` module as `import math`, then you would have to refer to all functions with `math.` prefix.

Please feel free to reopen this issue if this does not answer your question :)

**Comment by edsml-na506** [comment]
Thanks a lot @marijanbeg that makes sense!
Although the value I now get is 0.12098536225957168
The pybryt and ok checks say I have still done something incorrect?

**Comment by edsml-na506** [comment]
I figured out I was missing a set of brackets! 
All fine now.
