### ISSUE TITLE
Problem with exercise 2.12?

### ISSUE THREAD

**Issue by acse-4bc892f6** [ese-msc/introduction-to-python#20]
Hello,

I have written a code that should be correct and I have used the names of the variables as provided, but the okpy test indicates that C is undefined. Is there a problem with the okpy test?
![Screenshot 2021-09-02 at 10 08 12](https://user-images.githubusercontent.com/67314331/131816682-cfc629ed-a37e-434c-afb3-9b22b05617a3.png)
![Screenshot 2021-09-02 at 10 08 26](https://user-images.githubusercontent.com/67314331/131816687-6b0e8cd5-211d-4cb6-8d59-baee77de5914.png)

**Comment by marijanbeg** [comment]
Hi @acse-4bc892f6, thank you for your question. Exercise 2.12 asks you to do two things:
- Write function `f_mult`
- Using function `f_mult`, multiply matrices `A` and `B`, and put that matrix in variable `C`

It looks like you have not defined matrix `C` in your solution. Is that correct?

We are looking forward to hearing from you.

**Comment by acse-4bc892f6** [comment]
Hi @marijanbeg, I have created a zero matrix `C` before the loop, then populated `C` within the loop of the function `f_mult`.

**Comment by marijanbeg** [comment]
Hi @acse-4bc892f6, thank you for your clarification. You should also define the matrix `C` outside the function `f_mult`. For instance,

```python
A = ...
B = ...
def f_mult(...):
    ...

C = f_mult(A, B)
```

I agree that this was not explained well in the exercise and we will improve the exercise text (I will keep this issue open until the exercise requirements are better explained).

Please let us know if our suggestion fixed your issue.

**Comment by acse-4bc892f6** [comment]
Hi @marijanbeg, this fixed it. Thank you.

**Comment by marijanbeg** [comment]
Great. We addressed this issue by explaining the exercise requirements better.

Thank you very much for your valuable feedback. Please feel free to raise further issues :)
