### ISSUE TITLE
Exercise 2.11 pybryt

### ISSUE THREAD

**Issue by acse-4bc892f6** [ese-msc/introduction-to-python#22]
Hello,

In `f_cubic(A)`,  I created a zero matrix in the shape of A to be the solution matrix, then used two `for` loops to apply the function `f(x) = x**3+x*exp(x)+1` to each element in the matrix A and store the result in the solution matrix.

My code works and passed the okpy test, but it doesn't seem to be what the pybryt test was expecting? The pybryt test said I did not populate the resulting vector correctly and the result of my function is wrong.

![Screenshot 2021-09-02 at 17 12 25](https://user-images.githubusercontent.com/67314331/131879909-63482a4f-cd6a-4535-8a6a-11a0e740bcdb.png)
![Screenshot 2021-09-02 at 17 12 46](https://user-images.githubusercontent.com/67314331/131879915-6e65e2e9-a4c8-417f-a495-6f1b3684e212.png)

**Comment by acse-c2434dbb** [comment]
I have the same question. 
Also, I am not sure what are the 'two methods' that the exercise is referring to.

**Comment by marijanbeg** [comment]
Hi @acse-4bc892f6 and @acse-c2434dbb, thank you for your questions. We need to investigate this issue. Could you please share your solution code with us so that we can test PyBryt?

**Comment by acse-7d2f25c4** [comment]
I met the same problem. It is ok with okpy but wrong with pybryt. And here follows my code:

A33 = np.array([[0,12,-1],[-1,-1,-1],[11,5,5]])

def f_cubic(A):
    return A**3+A*np.exp(A)+1

A1 = np.zeros((3, 3))
for i in range(A1.shape[0]):
    for j in range(A1.shape[1]):
        A1[i, j] = f_cubic(A33[i, j])

A2 = f_cubic(A33)

print(A1==A2)

**Comment by marijanbeg** [comment]
Hi everyone, thank you for sharing your code. We investigated this issue and the PyBryt reference solution we provided is too restrictive. I can confirm that your solution is correct if it passes `okpy` tests.
