### ISSUE TITLE
Issue with exercise #1.11

### ISSUE THREAD

**Issue by acse-90469b93** [ese-msc/introduction-to-python#24]
Well this could be an stupid question but I am wondering what does this "divide by 10 in each iteration" mean since I think I am doing exactly what he asked me to do:
<img width="1098" alt="Screen Shot 2021-09-10 at 2 30 33 PM" src="https://user-images.githubusercontent.com/90373061/132810278-a9493b27-2f39-4be0-aeb4-01d5ec03e95d.png">

**Comment by acse-90469b93** [comment]
I tried to change  division '//' to '/'  but it still cannot pass the okpy test, so I am wondering what does the expected answer looks like.

**Comment by acse-7d2f25c4** [comment]
I encounted the same problem...

**Comment by acse-7d2f25c4** [comment]
I met the same problem...

**Comment by marijanbeg** [comment]
Hi @acse-90469b93 and @acse-7d2f25c4, thank you very much for your patience. We investigated this issue and the reason for this error is that our PyBryt reference solution is too restrictive. I can confirm that your solution is correct as long as it passes okpy tests. Unfortunately, expanding the PyBryt reference solution is not possible without introducing the changes to PyBryt itself, which can take some time. Therefore, please ignore the error messages raised by PyBryt and ensure your solution passes okpy tests :) We will introduce this fix in the next iteration.

Thank you very much for your valuable feedback, and please do not hesitate to raise further issues.
