### ISSUE TITLE
Question on  Exercise # 1.16: Position of the ball in a vertical motion.

### ISSUE THREAD

**Issue by acse-90469b93** [ese-msc/introduction-to-python#25]
Hi I two questions about this Exercise:

1,  How do we define the step of 't' within the given range? say if we have distance(1.4375,100,22),  what is the step value? Is it 0.0001?  How can we define a float list from a given range without import modules like numpy? By the way my code did not satisfy pybryt on input distance(0.1,0.6,5) but passed the test case in okpy, can someone share the code which satisfied?
REFERENCE: exercise-1_16
SATISFIED: False
MESSAGES:
  - ERROR: Hmmm... You are not iterating over the correct values of t.
  - ERROR: You are not appending the positions to a list.
  - SUCCESS: Before the loop, you start with an empty list. Amazing!
  - ERROR: Your time step value is wrong.
  - ERROR: Your function returns a wrong solution.

2 , I checked the test source code of okpy test, can somebody explain how to get this result on input distance(1,6,5,3)?  I do not think this is a correct answer.
![Screenshot 2021-09-11 130820](https://user-images.githubusercontent.com/90373061/132937336-edb02688-8a60-4118-b0cf-127d0e845b24.png)

**Comment by edsml-f8a1d4c7** [comment]
I used  ```step = (t_end - t_start) / (n - 1)``` to find the step. Hope this solves your problem:)
