### ISSUE TITLE
Question about Pybryt and Jupyter notebook installation 

### ISSUE THREAD

**Issue by acse-20449ecc** [ese-msc/introduction-to-python#26]
Sorry about I did not raise the issue until now.
As I mentioned previously in this [issue](https://github.com/ese-msc/introduction-to-python/issues/10), the Pybryt  cannot work properly on my machine.
Though everything works fine when I use Jupyter Lab, I will always receive the same error message ( ' ValueError: max() arg is an empty sequence' ) whenever I tried to run the Pybryt to check the same code on my own machine, no matter what the code does, like this one. 

> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> ~\AppData\Local\Temp/ipykernel_13396/4254411162.py in <module>
>       1 with pybryt.check(pybryt_reference(1, 11)):
> ----> 2     num_digits(999_999_999)
> 
> D:\STUDY\ANACONDA\envs\introduction-to-python\lib\site-packages\pybryt\student.py in __exit__(self, exc_type, exc_value, traceback)
>     422 
>     423     def __exit__(self, exc_type, exc_value, traceback):
> --> 424         tracing_off(save_func=False)
>     425 
>     426         if self._frame is not None:
> 
> ValueError: max() arg is an empty sequence

I suspect that the pybryt does not work properly because my installation, but am not sure that this error message is necessarily related to it. Months ago, after I installed jupyter notebook and tried to run the lectures on my machine, I kept encountering with the problem of dead kernel, and the Anaconda prompt gave error message like this

> ImportError: DLL load failed while importing win32api: 找不到指定的模块。

('找不到指定的模块' means 'The specified module could not be found')

And after lots of searching, I solved this problem by running these lines while I do not really understand what cause my problem either what exactly these lines actually do.

```
conda install -c conda-forge pywin32
conda install -c anaconda jupyter_client
conda install -c conda-forge jupyter_core
```

Is there anyway to fix the problem? Thank you very much in advance.

**Comment by marijanbeg** [comment]
Hi @acse-20449ecc, thank you for your question, and we are sorry you encountered this issue.

We recommend installing all packages you need for the pre-sessional materials using [`environment.yml`](https://github.com/ese-msc/introduction-to-python/blob/main/environment.yml) file. This way, we can ensure all your dependencies are correct and installed in a separate conda environment. You will learn about conda environments in Modern Programming Methods course :)

I suspect that, in your case, by installing JupyterLab and PyBryt separately, you installed `ipykernel >= 6.0` which is incompatible with PyBryt at the moment.

I will close this issue, but please feel free to reopen it if this does not resolve your issue. Thank you for your valuable feedback.
