### ISSUE TITLE
Question about pybryt: AttributeError: 'Value' object has no attribute '_values'

### ISSUE THREAD

**Issue by edsml-edfca981** [ese-msc/introduction-to-python#32]
To whom it may concern,

I have finished several Exercises, and when I used the pybryt to check about it, all of them will have the attributeerror. 

It confused me for I want to fix my code but do not know how. And, for the easiest exercise, I do not think there is another way to solve the problem following the instructions.

I am looking forward to your reply.

Thanks

**Comment by marijanbeg** [comment]
Hi @edsml-edfca981, thank you for your question. The PyBryt installed on JupyterHub is outdated (0.2.0), which is why you are receiving this error.

@rolotumazi, it seems PyBryt version is hardcoded somewhere in your scripts. Could you please have a look if we can update PyBryt?

**Comment by rolotumazi** [comment]
@marijanbeg , I've updated pybryt to version 0.7.0 in the image used.

**Comment by marijanbeg** [comment]
Thank you @rolotumazi! @edsml-edfca981, this fixes the issue. Therefore, I am closing it. If you encounter any further issues, please do not hesitate to open a new issue. :)

**Comment by edsml-edfca981** [comment]
Thanks for your updating. PyBryt works fine now!
