### ISSUE TITLE
Issue with scoring in lecture2 - ok.score()

### ISSUE THREAD

**Issue by acse-sm222** [ese-msc/introduction-to-python#34]
Just wanted to point out that in lecture2, when the final score is calculated using ok.score(), question 2.10 is not evaluated correctly. This is because the variable b, as used in Exercise 2.10 is redefined in code cell In [76] (example demonstrating the usage of @ operator). Changing the variable name in this example solves this.

**Comment by marijanbeg** [comment]
Hi @acse-5e87d041, thank you very much for letting us know. We will take this suggestion into account when we review the lectures.

**Comment by marijanbeg** [comment]
okpy abandoned
