### ISSUE TITLE
Question on Exercise 3.3: How can I use an element in array in label?

### ISSUE THREAD

**Issue by edsml-edfca981** [ese-msc/introduction-to-python#35]
#my codes are contained in """ """.
Hello!

In exercise 3.3, we are asked to plot the function with 10 values of v0. Therefore, I set the v0 with np.linspace(0,20,10) and put it into function y(v0,g) set by myself:
"""def y(v0,g):
    t_max=2*v0/g
    t=np.linspace(0,t_max,51)
    y=v0*t-1/2*g*t**2
    plt.plot(t,y)"""

However, I want to show the v0's value to each curve in legend. And I tried several methods, but they didn't work.

First, I used """label=f"$v_0=${v0:}"  """in plot function. And the result showed in axes contained the whole array in legend of each curve.
<img width="500" alt="截屏2022-08-08 11 53 50" src="https://user-images.githubusercontent.com/110276317/183335732-45ccb33f-cc8d-4717-9ad8-0daeb615b80e.png">

Secondly, I tried to find the index of specific value in array and used it in legend.  However, I found that it is difficult to locate the specific value of v0 in function y by used:
"""def y(v0,g):
    t_max=2*v0/g
    t=np.linspace(0,t_max,51)
    y=v0*t-1/2*g*t**2
    v=v0
    n=np.where(v0==v)
    plt.plot(t,y,label=f"$v_0=${v0[n]}") """     #have the same result with First method

or
"""n=0
def y(v0,g,n):
    t_max=2*v0/g
    t=np.linspace(0,t_max,51)
    y=v0*t-1/2*g*t**2
    plt.plot(t,y,label=f"$v_0=${v0[n]}")
    n=n+1
    
v0= np.linspace(1,20,10)
g=9.81
res= y(v0,g,n)"""   # it seems that n don't change in the code.
<img width="473" alt="截屏2022-08-08 12 02 33" src="https://user-images.githubusercontent.com/110276317/183336561-24cae92d-d889-4918-8c5f-94670b768976.png">

Overall, I don't know how to realize it.

I am looking forward to your reply.

Thanks

**Comment by acse-5e87d041** [comment]
I am not sure if I can share my code here. But here is the idea:
Do the plotting inside a for loop iterating over each value of v0 - i.e. a plt.plot(t, y, legend="v0 = {v}") in each iteration for v in v0 array. Then use plt.show(), title, labels and legend location at the end outside the for loop.
![download](https://user-images.githubusercontent.com/110117790/183348211-b2ea8e2f-36c8-49b1-9d6d-0240951c91a0.png)

**Comment by edsml-edfca981** [comment]
> I am not sure if I can share my code here. But here is the idea: Do the plotting inside a for loop iterating over each value of v0 - i.e. a plt.plot(t, y, legend="v0 = {v}") in each iteration for v in v0 array. Then use plt.show(), title, labels and legend location at the end outside the for loop. ![download](https://user-images.githubusercontent.com/110117790/183348211-b2ea8e2f-36c8-49b1-9d6d-0240951c91a0.png)


Thanks for your advice!

I have solved it.
