### ISSUE TITLE
Report some trivial bugs that may encounter while running via a local machine

### ISSUE THREAD

**Issue by KennardWang** [ese-msc/introduction-to-python#37]
### Exercise 1.6
**Bug**
 `ok.score()` failed to evaluate the score of ex1.6 but it evaluated twice on ex1.5.

**How to fix**
In `lecture1\okpy-tests\exercise-1_6.py`, modify

```
test = {
    'name': 'question 1.5',
    'points': 1,
    'suites': [
...
```
to
```
test = {
    'name': 'question 1.6',
    'points': 1,
    'suites': [
...
```

<hr>

### Exercise 2.10
**Bug**
`ok.score()` said the result `b` was incorrect but actually there was no error when we tested ex2.10 individually. This problem was probably caused by the variable name `b` appeared in [In [76]:](https://github.com/KennardWang/introduction-to-python-with-answer/blob/master/lecture2/lecture2.ipynb)

```
A = np.array([[1, 1], [2, 1]])
b = np.array([1, 2])
Ab = A @ b

print(f"{A}")
print(f"{b}")
print(f"{Ab}")
```

**How to fix**
Changing the variable name may fix this bug. For example, I use `b_vector` instead.

<hr>

### Exercise 2.13
**Bug**
The requirements of the questions seemed not to correspond to the given answer. 

**How to fix**
I guess the third point of the requirements may be: 
+ Using array slicing, create a 2D NumPy array called, odd_bits, that starts from the 2nd column of odd_sq and selects every other `even` column, of only the 2nd and 3rd rows of odd_sq.

And here is the given answer:
```
odd_sq =
[[ 1  3  5  7  9 11 13]
 [15 17 19 21 23 25 27]
 [29 31 33 35 37 39 41]
 [43 45 47 49 51 53 55]]

odd_bits =
[[17 21 25]
 [31 35 39]]
```

<hr>

### f-string print bug in lecture 2 & 4
**Bug**
It may cause a syntax error.

**How to fix**
Delete the `=` or move it out of the `{}`.

<hr>

I leave my notebook answer [here](https://github.com/KennardWang/introduction-to-python-with-answer) as a reference even though it is not the perfect one. By the way, my env is `Windows10` with `Python3.7`, and I am not sure how other platforms perform. Hope that can help you.

**Comment by marijanbeg** [comment]
Hi @KennardWang, thank you very much for pointing to those issues. We will analyse them and include them in the next release if necessary. If you discover any further problems, we would be grateful if you could let us know.

**Comment by marijanbeg** [comment]
okpy is not used any longer
