### ISSUE TITLE
Solution for Exercise 4.1

### ISSUE THREAD

**Issue by gems-f82bc586** [ese-msc/introduction-to-python#38]
Hello guys! Could you please show me your solution for exercise 4.1? I obtained a proper result, but the whole process of extracting the data from the file is wrong (it works in this specific case, but it won't work in general). 

<img width="515" alt="Снимок экрана 2022-09-18 в 23 15 24" src="https://user-images.githubusercontent.com/110783714/190926613-58139401-56be-4d62-a2a5-73acf266f967.png">

**Comment by edsml-1442c4e5** [comment]
Hi do you figure out the solution for 4.1? Can I look ot your code please I have the same problem:(
