### ISSUE TITLE
issues with exercise 1.18 bouncing ball

### ISSUE THREAD

**Issue by edsml-1442c4e5** [ese-msc/introduction-to-python#39]
Hi here is my code for excercise 1.18 and it turns out to be a error. However when i compute this in pycharm, it gives the correct answer.

def compute_heights(h_0=1.0, h_1=0.3, n=10):
    l=[]
    h=h_0
    for n in range(10):
        if h>=h_1:
            h=h_0*0.9**n
            l.append(h)
    return l

**Comment by edsml-1442c4e5** [comment]
def compute_heights(h_0=1.0, h_1=0.3, n=10):
    l=[]
    h=h_0
    for n in range(10):
        h=h_0*0.9**n
        l.append(h)
        if h<h_0:
            break
    return l
       
I add 'break' to check if the height is less than h_1, it works on my pycharm, but still errors in the lecture

**Comment by acse-6f9303e2** [comment]
Hi! I can just solve your problem. 
I just tried to run your code (first post). I think your problem is that you don't understand the meaning of the question. 
**n represents the number of bounces.** 
**When it bounces to the 10th time, the height of the ball should be h_0*0.9**10.** 
You're looking at the original height as the height after the first bounce, which I guess is wrong.

**Comment by edsml-1442c4e5** [comment]
> 



> Hi @edsml-1442c4e5, is the error reported by okpy, pybryt, or both. Could you please show us the error message so that we can understand where the problem is?

Hi! I run it correctly at the second day I post this issue. Just a careless mistake, I should break after h_1 but accidently wrote h_0 in my code. Thank you for your response I will close this issue now

**Comment by edsml-1442c4e5** [comment]
> Hi! I can just solve your problem. I just tried to run your code (first post). I think your problem is that you don't understand the meaning of the question. **n represents the number of bounces.** **When it bounces to the 10th time, the height of the ball should be h_0*0.9**10.** You're looking at the original height as the height after the first bounce, which I guess is wrong.

Hi! Thank you for your response! I found out where am I wrong. I should replace h_0 by h_1 in the breaking condition, it is really careless for me:(

**Comment by edsml-1442c4e5** [comment]
here is my code and the full error messages. I try this in pycharm and it gives me a list with 11 element including the initial height h_0, when n=10. 
def compute_heights(h_0,h_1,n):
    l=[]
    for i in range(n+1):
        h=h_0*0.9**i
        l.append(h)
        if h<h_1:
            break
    return l
compute_heights(h_0=1.0, h_1=0.3, n=10)


REFERENCE: exercise-1_18
SATISFIED: False
MESSAGES:
  - SUCCESS: You are appending the correct height to a list. Well done!
  - ERROR: You are not counting the bounces correctly.
  - SUCCESS: Before the loop, you start with an empty list. Amazing!
  - SUCCESS: Before the loop, you set the ounter to zero. Great!
  - SUCCESS: Wow! Your function returns the correct solution.


Running tests

---------------------------------------------------------------------
question 1.18 > Suite 1 > Case 1

import numpy as np
>>> np.allclose(compute_heights(), [1.0, 0.9, 0.81, 0.7290000000000001, 0.6561000000000001, 0.5904900000000002, 0.5314410000000002, 0.47829690000000014, 0.43046721000000016, 0.38742048900000015, 0.34867844010000015])
TypeError: compute_heights() missing 3 required positional arguments: 'h_0', 'h_1', and 'n'

# Error: expected
#     True
# but got
#     Traceback (most recent call last):
#       ...
#     TypeError: compute_heights() missing 3 required positional arguments: 'h_0', 'h_1', and 'n'

Run only this test case with "python3 ok -q exercise-1_18 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    Passed: 0
    Failed: 1
[k..........] 0.0% passed

{'passed': 0, 'failed': 1, 'locked': 0}
