### ISSUE TITLE
Exercise 1.18 okby test

### ISSUE THREAD

**Issue by acse-4bc892f6** [ese-msc/introduction-to-python#4]
The okby test for exercise 1.18 has a maximum height less than 0.3 (h_1) in the list. Is the test correct?

`>>> np.allclose(compute_heights(h_0=0.5), [0.5, 0.45, 0.405, 0.36450000000000005, 0.32805000000000006, 0.2952450000000001])`

**Comment by marijanbeg** [comment]
Hi @acse-4bc892f6, thank you for your question! Exercise requires you to: "Write a Python function compute_heights that returns a list of the maximum heights of the ball after each bounce (including after 0 bounces, i.e. its initial height), until either the ball has bounced `n` times **or its maximum height falls below `h1`**." This means that the last height value in the resulting list should be the value that is less than `h1` (less than 0.3 in this case). More precisely, it is the first value of height below `h1`.

I agree with you that this could be confusing, and we will add a more explicit explanation to the exercise. :)

Thank you very much for your feedback, and please do not hesitate to raise further issues.

(issue open until resolved and released)

**Comment by acse-4bc892f6** [comment]
Hi, thanks for your reply. But it seems that in case 1 the same test requires the elements in the list to be not less than 0.3:

`question 1.18 > Suite 1 > Case 1

import numpy as np
>>> np.allclose(compute_heights(), [1.0, 0.9, 0.81, 0.7290000000000001, 0.6561000000000001, 0.5904900000000002, 0.5314410000000002, 0.47829690000000014, 0.43046721000000016, 0.38742048900000015, 0.34867844010000015])`

Whereas for case 2, one element is less than 0.3:

`question 1.18 > Suite 1 > Case 2

import numpy as np
>>> np.allclose(compute_heights(h_0=0.5), [0.5, 0.45, 0.405, 0.36450000000000005, 0.32805000000000006, 0.2952450000000001])`

Wouldn't this contradict each other?

**Comment by marijanbeg** [comment]
Hi @acse-4bc892f6, thank you for the clarification. In the first case, the last value is larger than `h1` because the loop stopped after `n=10` bounces, and the height did not manage to fall below 0.3. Please let us know if this does not answer your question.

**Comment by acse-4bc892f6** [comment]
I see. Thank you!

**Comment by marijanbeg** [comment]
Thank you once again for your feedback, and please do not hesitate to raise further issues. :)
