### ISSUE TITLE
Exercise 1.9 in lecture 1

### ISSUE THREAD

**Issue by gems-68239853** [ese-msc/introduction-to-python#47]
This is my code:

# Uncomment and complete this code - keep the names the same for testing purposes.

from math import pi, sqrt

def period(a, m_planet, m_sun=2e30, G=6.67e-11):
    P_mars = sqrt(4*pi**2*(1.5*a)**3/(G*(m_sun + 0.1*m_planet)))
    P_earth = sqrt(4*pi**2*a**3/G/(m_sun + m_planet))
    birthdays = 10*P_mars/P_earth
    return P_mars, P_earth, birthdays

but when I test it by pybryt, it shows this comment below:

REFERENCE: exercise-1_9
SATISFIED: False
MESSAGES:
  - SUCCESS: Your function computes the period correctly.
  - SUCCESS: You computed the Earth's period correctly.
  - ERROR: You are not computing Mars's period correctly.
  - SUCCESS: Wow! Your computed birthdays value is correct!

What is wrong with my code?

**Comment by marijanbeg** [comment]
Hi @gems-68239853, thank you for raising the issue and we hope you enjoy working on your Python exercises.

Function `period` should compute and return the period of a single planet. Then you should call it separately for Mars and for Earth. In your case, you are computing all periods, including birthday in the function, and return a tuple. We believe that fixing this would make PyBryt tests pass.

**Comment by gems-68239853** [comment]
Hello Mr. Marijanbeg, thank you for responding to me.

Thank you for the hint, I fixed my code and it worked perfectly!

**Comment by marijanbeg** [comment]
Great, thank you for letting us know.
