### ISSUE TITLE
Exercise 1.9 for Lec1

### ISSUE THREAD

**Issue by acse-17b3c37e** [ese-msc/introduction-to-python#48]
For this exercise, the pybryt check is correct. See the screenshot below.
![image1](https://github.com/ese-msc/introduction-to-python/assets/142551505/73788db4-0644-48e1-9b67-0fb2ec8a38e9)

However, there is some problem for assert whether res equals to 2*pi. Maybe this assert should be assert whether res equals pi*2e-15?
![image2](https://github.com/ese-msc/introduction-to-python/assets/142551505/1ff7820c-82b4-4916-919e-439a8356d1d6)

**Comment by acse-17b3c37e** [comment]
And all the following assert are correct if comment this assert
![image3](https://github.com/ese-msc/introduction-to-python/assets/142551505/0443e2b8-0655-4550-bca3-a3de9d0df105)

**Comment by acse-17b3c37e** [comment]
Sorry My Mistake

**Comment by marijanbeg** [comment]
No problem at all :)
