### ISSUE TITLE
Problem with Exercise 2.8

### ISSUE THREAD

**Issue by acse-17b3c37e** [ese-msc/introduction-to-python#49]
I tried several ways but still error for this function...I am not sure what the test for this function is going to check. Both the x array and y array are correct.
![imagee](https://github.com/ese-msc/introduction-to-python/assets/142551505/dea4f14d-9bf3-4230-b6a0-1cf958dd2cee)

**Comment by marijanbeg** [comment]
HI @acse-17b3c37e, have you tried using `math.exp` function instead of `e ** ...`.

**Comment by acse-17b3c37e** [comment]
> HI @acse-17b3c37e, have you tried using `math.exp` function instead of `e ** ...`?

Thanks for your reply! 

I have tried `math.exp` previously but it occurs an error. I did not realize why this error happens.

Your hint remind me that functions in `math` library cannot be vectorized. I should use math function in `numpy` library for vectorization!

Thanks for your help again~

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. :)
