### ISSUE TITLE
Problem with opening notebook

### ISSUE THREAD

**Issue by edsml-a5a334c7** [ese-msc/introduction-to-python#50]
cannot open or access file:///home/jovyan/.local/share/jupyter/runtime/nbserver-1193-open.html 

urls do not exist

**Comment by marijanbeg** [comment]
Hi @edsml-a5a334c7, thank you for raising the issue. Could you please let us know more details, such as where are you running the notebook, what machine and operating system you use, etc.

**Comment by edsml-a5a334c7** [comment]
I am using a MacBook Pro 13, and I have tried running the git clone on both Safari and Chrome. I managed to circumvented the issue by downloading GitHub Desktop, however still cannot access the files using the original method. 

Thanks,

Caoimhe

**Comment by edsml-a5a334c7** [comment]
I have yes. I installed Homebrew and Xcode Command Line Tools (although I am aware that they are redundant) as well. I am currently working through the exercises but I am curious about what was going wrong prior to my installation of GitHub Desktop so that it does not prove an issue in the future.

**Comment by marijanbeg** [comment]
Hi @edsml-a5a334c7, I do not understand from your previous message if you managed to run the notebook locally in the end. Could you please clarify?

**Comment by marijanbeg** [comment]
Hi @edsml-a5a334c7, could we please have an update on this issue?

**Comment by edsml-a5a334c7** [comment]
It has been resolved. Thank you so much for your help. Best,CaoimheOn Aug 24, 2023, at 6:01 AM, Marijan Beg ***@***.***> wrote:﻿
Hi @edsml-a5a334c7, could we please have an update on this issue?

**Comment by edsml-a5a334c7** [comment]
I am still unsure why the original git clone command, run from the terminal did not work initially, but it seems to be working now. Thanks,Caoimhe On Aug 24, 2023, at 9:26 AM, Caoimhe Chan ***@***.***> wrote:﻿It has been resolved. Thank you so much for your help. Best,CaoimheOn Aug 24, 2023, at 6:01 AM, Marijan Beg ***@***.***> wrote:﻿
Hi @edsml-a5a334c7, could we please have an update on this issue?

**Comment by marijanbeg** [comment]
Thank you for letting us know. I will close this issue now.
