### ISSUE TITLE
Failing pybryt test but succeeding assert tests

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#54]
I am working through the exercises on the online jupyter workbooks but keep getting the same error as seen below for all my exercises. When I test the code with the assert tests, it passes. Not sure what I am missing
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[94], line 1
----> 1 with pybryt.check(pybryt_reference(1, 4)):
      2     p, A_0, n, A_n

NameError: name 'pybryt_reference' is not defined

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, did you run the first cell in the notebook which contains `from lecture import pybryt_reference`?

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. I will close this issue now.
