### ISSUE TITLE
How to open the jupyter notebook from local files

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#55]
Apologies if this a really daft question. I am using the online jupyter workbooks to work through the exercises with no anaconda environment installed on my macbook. I am unsure of how to open the locally saved jupyter workbook in the online sessions to continue my work without losing my progress.

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, thank you for your question. Since you have closed this issue, does that mean you managed to find a way how to download the notebook and then upload it later? If yes, I would suggest explaining it here so that your colleagues can find the answer if they need to.

**Comment by acse-92d36642** [comment]
yes, there was an option to download the workbook in the file menu. I downloaded the workbook there. Then I was able to upload the file to the jupyterlab. The issue I then faced was when uploading the file back to jupyterlab, it could not find the lecture.py file to carry out the pybryt testing However, moving it to the same directory as the lecture.py as mentioned in issue #53 seemed to work

**Comment by marijanbeg** [comment]
Great, thank you.
