### ISSUE TITLE
pybryt not importing

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#56]
Pybryt is not importing after I uploaded a saved workbook to continue my work,
<img width="1099" alt="Screenshot 2023-08-24 at 23 35 41" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/40050da7-6142-4f56-adaa-e6e8b9b908de">

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, thank you for your question. Your notebook file must be in the same directory as `lecture.py` file. Please refer to #53 for more details.
