### ISSUE TITLE
Errors in Exercise 2.10

### ISSUE THREAD

**Issue by edsml-10f37f99** [ese-msc/introduction-to-python#59]
Hi, I have solved this exercise with the requirements as I understand but getting the below errors.
ERROR: Your vector b is wrong.
  - ERROR: You are not populating resulting vector correctly.
  - ERROR: Consider creating a zero vector before the loop.
  - ERROR: Hmmm... The result of your multiplication is wrong.

Is the answer expected in some other format? I solved the matrix manually and the answer is correct.
PFA my solution below:
![image](https://github.com/ese-msc/introduction-to-python/assets/142841458/376842bf-59bc-40a0-a066-0d010b95cab7)

Thanks!

**Comment by marijanbeg** [comment]
Hi @edsml-10f37f99, thank you for raising this issue. The elements of the matrix you compute are correct. However, the shape of numpy arrays is not as expected. Could you please define vector `b` as a row vector and modify your code accordingly? Please let us know if this solved your issue?

```
A = np.array([[0, 12, -1], [-1, -1, -1], [11, 5, 5]])
b = np.array([-2, 1, 7])
c = multiply(A, b)
```

**Comment by edsml-10f37f99** [comment]
As per the question, the vector defined is of shape 3,1 (a column vector). If we convert it into a row vector, the shape would change to 1,3. 
Wouldn't that change the question here?
Pls, correct me if my understanding is incorrect here.

Thanks!

**Comment by marijanbeg** [comment]
Hi @edsml-10f37f99, array `np.array([[1], [1], [1]])` has shape `(3, 1)`, whereas `np.array([1, 1, 1])` has shape `(3,)`. The reference solution we use in this case requires shape `(3,)`.
