### ISSUE TITLE
Exercise 2.2 - nested list incorrect

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#60]
Not entirely sure why my nested list solution is wrong. I get the correct values for ylist and tlist, and just created a new list with variable name displacement where ylist and tlist are the elements

<img width="1248" alt="Screenshot 2023-08-31 at 16 13 53" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/d90fe205-932e-4e05-b774-e70c290b003f">

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, thank you for your question. If `a` is a list, then `[a]` will create a list in a list. `displacement` should be defined as:

```
displacement = [list, ylist]
```

I hope this answers your question. Please feel free to reopen this issue.
