### ISSUE TITLE
Question 2.11 in lecture 2

### ISSUE THREAD

**Issue by gems-68239853** [ese-msc/introduction-to-python#62]
Can I know my mistake for my code, I could not figure it out.

**Comment by gems-68239853** [comment]
![IMG_0004](https://github.com/ese-msc/introduction-to-python/assets/142586952/b1651cca-158d-4ff7-a917-f26493941f93)

**Comment by marijanbeg** [comment]
Hi @gems-68239853, thank you for raising this issue. PyBryt reference solution we use for this exercise expects the for loop to be used inside `f_cubic` function. In other words, `f_cubic` function takes a metric as an input and returns matrix. I hope this clarifies the requirements of this exercise. Please feel free to reopen this issue or comment if we can provide further information.

**Comment by gems-68239853** [comment]
I tried to understand your comment and I updates the code as shown below:

![IMG_0007](https://github.com/ese-msc/introduction-to-python/assets/142586952/8c54d6fe-758c-4b11-b03b-543980fc12c3)


it only solved the second comment:

REFERENCE: exercise-2_11
SATISFIED: False
MESSAGES:
  - ERROR: You are not populating resulting vector correctly.
  - SUCCESS: You created a zero-matrix before looping.
  - ERROR: Hmmm... The result of your function is wrong.
  - SUCCESS: Your matrix A33 is correct.

**Comment by marijanbeg** [comment]
Hi @gems-68239853, do the assert statements in the cell below pass?

**Comment by acse-92d36642** [comment]
I am having similar problems with the exercise
<img width="651" alt="Screenshot 2023-09-06 at 19 15 45" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/c0021ec3-b9a9-4366-8534-34fc3136ecb5">
The pybryt solution doesn't seem to accept my solution. Not getting any issues with assert tests though

**Comment by gems-68239853** [comment]
The assert statements shows nothing when I press (shift+enter) to run it, assuming it passed successfuly.
