### ISSUE TITLE
Clarification of exercise 2.10

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#63]
<img width="939" alt="Screenshot 2023-09-05 at 17 03 36" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/f77f5207-e13c-48c9-b765-e880541226bc">
I created the matrix and the vector, but the solution says my resultant vector is not populated correctly. Not sure how to correct that. Did the solution want the array as a column shape?

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, `multuply` function must be implemented using `for` loops, instead of simply calling `np.matmul`. I hope this answers your questions, please do not hesitate to reopen this issue or comment if you need further assisstance.
