### ISSUE TITLE
Exercise 3.3, graph legend not displaying properly

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#69]
I am having some trouble with assigning the correct labels to the curves. I am iterating through the values of Y and trying to get the correct labels on the legends but as per the image, I am getting the whole array as the legend of the line. Not sure how I can fix this

import numpy as np
import matplotlib.pyplot as plt

v0=np.linspace(0,20,10)
g=9.81
t=np.linspace(0,(2*v0/g))

def f(v0,t,g):
    return v0*t-(0.5*g*t**2)
y=f(v0,t,g)

def graph(t,y):
    f(v0,t,g)
    for i in y:
        plt.plot(t,y,label=f"V0={i}")
    plt.xlabel("t")
    plt.ylabel("v0")
    plt.legend()
    plt.show()
graph(t,y)
<img width="605" alt="Screenshot 2023-09-11 at 18 46 05" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/0d6a7f41-fe7f-4f0d-9528-72b919a4ff41">

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, thank you for raising this issue. Please pay attention to what the value of `i` is inside the `for` loop since this is the value you are using to create a legend.

**Comment by acse-92d36642** [comment]
Thank you for advice @marijanbeg. I have adjusted the code but I am still creating multiple labels where I need only one.

import numpy as np
import matplotlib.pyplot as plt

v0=np.linspace(0,20,10)
g=9.81
t=np.linspace(0,(2*v0/g))

def f(v0,t,g):
    return v0*t-(0.5*g*t**2)

y=f(v0,t,g)

def graph(t,y):
    f(v0,t,g)
    for v in v0:
        plt.plot(t,y,label=f"V0={v}")
    plt.xlabel("t")
    plt.ylabel("v0")
    plt.legend()
    plt.show()
graph(t,y)

As I am using a for loop to do the plotting, a new label for the same value of v0 seems to be created every iteration. However, if I plot outside of the loop, then I get the whole array as the legend. 


<img width="498" alt="Screenshot 2023-09-12 at 14 17 32" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/9f1904f8-e99c-401a-aced-ddb1e96a873b">

**Comment by marijanbeg** [comment]
Hi @acse-92d36642, it is difficult to understand from your code what belongs to the function and what does not. Could you please show us your code with indentations. Please note that your can use ``` around the lines of code to be able to include indentations.

**Comment by acse-92d36642** [comment]
Thank you for responding @marijanbeg, I hope this makes it clearer

```import numpy as np
import matplotlib.pyplot as plt

v0=np.linspace(0,20,10)
g=9.81
t=np.linspace(0,(2*v0/g))

def f(v0,t,g):
    return v0t-(0.5g*t**2)

y=f(v0,t,g)

def graph(t,y):
    f(v0,t,g)
    for v in v0:
    plt.plot(t,y,label=f"V0={v}")

plt.xlabel("t")
plt.ylabel("v0")
plt.legend()
plt.show()

graph(t,y)```

**Comment by marijanbeg** [comment]
Thank you for your code. The issue is that you generate `t` array only once using `v0` which is an array. This results in a matrix instead of a 1D array. Here is the correction:

```
v0=np.linspace(0,20,10)
g=9.81

def f(v0,t,g):
    return v0*t-(0.5*g*t**2)


for v in v0:
    t=np.linspace(0,(2*v/g))
    plt.plot(t, f(v,t,g),label=f"V0={v}")

plt.xlabel("t")
plt.ylabel("v0")
plt.legend()
plt.show()
```

**Comment by acse-92d36642** [comment]
Thank you so much, it makes a lot more sense now. I missed that I was only creating the t array once.
