### ISSUE TITLE
exercise 1.18

### ISSUE THREAD

**Issue by edsml-8b751625** [ese-msc/introduction-to-python#70]
here is my code:

def compute_heights(h_0=1.0, h_1=0.3, n=10):
    h_list = []
    for i in range(n+1): 
        h_list.append(h_0*0.9**i)
    return h_list
    
   I get this when running the pybryt: I can't seem to fix the 2nd error
   
   REFERENCE: exercise-1_18
SATISFIED: False
MESSAGES:
  - SUCCESS: You are appending the correct height to a list. Well done!
  - ERROR: You are not counting the bounces correctly.
  - SUCCESS: Before the loop, you start with an empty list. Amazing!
  - SUCCESS: Before the loop, you set the ounter to zero. Great!
  - SUCCESS: Wow! Your function returns the correct solution.

**Comment by marijanbeg** [comment]
HI @edsml-8b751625, could you please let us know what assert statement is failing and what the error message is?

**Comment by edsml-8b751625** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 12
     10 ### BEGIN HIDDEN TESTS
     11 assert callable(compute_heights)
---> 12 assert np.allclose(compute_heights(h_0=1.0, h_1=0.5, n=10),
     13                    [1.0, 0.9, 0.81, 0.7290000000000001, 0.6561000000000001, 0.5904900000000002, 0.5314410000000002, 0.47829690000000014])
     14 ### END HIDDEN TESTS

File /opt/conda/lib/python3.10/site-packages/numpy/core/numeric.py:2241, in allclose(a, b, rtol, atol, equal_nan)
   2170 @array_function_dispatch(_allclose_dispatcher)
   2171 def allclose(a, b, rtol=1.e-5, atol=1.e-8, equal_nan=False):
   2172     """
   2173     Returns True if two arrays are element-wise equal within a tolerance.
   2174 
   (...)
   2239 
   2240     """
-> 2241     res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
   2242     return bool(res)

File /opt/conda/lib/python3.10/site-packages/numpy/core/numeric.py:2351, in isclose(a, b, rtol, atol, equal_nan)
   2349 yfin = isfinite(y)
   2350 if all(xfin) and all(yfin):
-> 2351     return within_tol(x, y, atol, rtol)
   2352 else:
   2353     finite = xfin & yfin

File /opt/conda/lib/python3.10/site-packages/numpy/core/numeric.py:2332, in isclose.<locals>.within_tol(x, y, atol, rtol)
   2330 def within_tol(x, y, atol, rtol):
   2331     with errstate(invalid='ignore'), _no_nep50_warning():
-> 2332         return less_equal(abs(x-y), atol + rtol * abs(y))

ValueError: operands could not be broadcast together with shapes (11,) (8,)

**Comment by edsml-8b751625** [comment]
please note that I'm 'sticking' to the lecture as in not using anything other than a for loop or a while loop (no if statements, break, etc.)

**Comment by marijanbeg** [comment]
Hi @edsml-8b751625, I would suggest looking at issue #51 and comparing your solution.
