### ISSUE TITLE
Exercise 3.4 AssertionError: 

### ISSUE THREAD

**Issue by gems-c02ae208** [ese-msc/introduction-to-python#71]
Hi, in exercise 3.4, I didn't pass the "with pytest.raises(ValueError):" check, but I did not know where I was wrong. Can you help me figure it out? Thank you!

**Comment by gems-c02ae208** [comment]
Here is the code picture
<img width="1155" alt="123" src="https://github.com/ese-msc/introduction-to-python/assets/142981910/f7e971c8-d1aa-43c1-b8e6-ab46eb3b5ae5">
<img width="1097" alt="12345" src="https://github.com/ese-msc/introduction-to-python/assets/142981910/701aecc3-3163-4b37-a178-f2257652c822">

**Comment by marijanbeg** [comment]
Hi @gems-c02ae208, thank you for raising the issue. Please note that `g` is an input parameter to your function. Please do not hard-code it (write `9.81` instead of `g` in the formula).
