### ISSUE TITLE
exercise 2-11 vectorized function

### ISSUE THREAD

**Issue by gems-a55c7bf2** [ese-msc/introduction-to-python#72]
Hi, in exercise 2-11, after writing the f_cubic function, I got 2 errors from the pybryt check:
ERROR: You are not populating resulting vector correctly
ERROR: Hmmm... The result of your function is wrong.

I got no error at all on the assertion cell. Looking at it, it is interesting to see that the assertion cell has np.allclose(f_cubic(A33), np.power(A33, 3) + np.multiply(A33, np.exp(A33)) + 1) which means that the f_cubic function written is outputting the correct array. What exactly the result that the PyBryt expect to be return from the function so that the second ERROR goes right?

And for the first error, I have tried different forms of iteration (using i and j separately, using np.ndenumerate), is there any hints to what the PyBryt expect for the first ERROR?

Thanks!

**Comment by gems-a55c7bf2** [comment]
My code for reference 
<img width="701" alt="image" src="https://github.com/ese-msc/introduction-to-python/assets/143512126/7b32d8a9-a9d3-4757-8c44-351f75e1d46d">

**Comment by marijanbeg** [comment]
Hi @gems-a55c7bf2, if the `assert` tests are passing, then your solution is correct. PyBryt tests are failing because our reference solution does not cover yours.
