### ISSUE TITLE
Exercise 3.9

### ISSUE THREAD

**Issue by acse-92d36642** [ese-msc/introduction-to-python#73]
<img width="1250" alt="Screenshot 2023-09-15 at 12 52 19" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/f3f999ec-fb54-4a62-aa45-bd196f099a46">
Hi, I am trying to complete exercise 3.9 but I cannot seem to create an numpy array. I keep getting an error that numpy.ndarray is not callable. Not sure how to rectify this issue.

```
import numpy as np
import matplotlib.pyplot as plt

with open ("data/acc.dat","r") as data_file:
    lines=data_file.readlines()
    acc_list=[]
    for line in lines:
        acc_list.append(line)
acc_array=np.array(acc_list)```

**Comment by marijanbeg** [comment]
Thank you for your question. Could you please let us know what are the values of:
- `acc_array`
- `acc_list`
- `np.array`

**Comment by acse-92d36642** [comment]
Thank you for your prompt response. When I print out the value of acc_list. I get the values as shown in the attached image. There are no values being assigned to acc_array or np.array due to the error being presented in the original comment.
<img width="1248" alt="Screenshot 2023-09-15 at 14 24 55" src="https://github.com/ese-msc/introduction-to-python/assets/142987763/ae62e0e8-e986-44dd-827d-564674495337">

**Comment by marijanbeg** [comment]
Could you please modify `acc_list.append(line)` to `acc_list.append(float(line))`?

**Comment by acse-92d36642** [comment]
Thank you for your response. It decided to work today. I tried it with your suggestion and it worked, but just  to test it I ran it again without the float method and it still created a numpy array

**Comment by marijanbeg** [comment]
Thank you for letting us know, @acse-92d36642. My assumption was that you accidentally overwrote `np.array` with a string, which resulted in that error. This is why I asked you to give us the output of `np.array`. I will close this issue now.
