### ISSUE TITLE
3.8 - what does the assert error mean? 

### ISSUE THREAD

**Issue by edsml-8b751625** [ese-msc/introduction-to-python#75]
Hello, here is my code for 3.8 

![image](https://github.com/ese-msc/introduction-to-python/assets/143718317/8514ea52-55b6-43d0-b207-afed9b9ba0b7)
(note: the commented code below it is another way and it gave me the exact same result and issue)

and this is the successful result with pybryt

![image](https://github.com/ese-msc/introduction-to-python/assets/143718317/a00faa28-d58b-42be-ac30-9ec3de328206)

but it does not pass the assert test, this is what it says:

![image](https://github.com/ese-msc/introduction-to-python/assets/143718317/690a09a6-bd69-4d71-a71c-2e1249cd9df9)

**Comment by marijanbeg** [comment]
Hi @edsml-8b751625, thank you for raising this issue. The assert statement fails because it is expected that the first element of `temp_air_list` is -10.

**Comment by edsml-8b751625** [comment]
oh God.. sometimes we get stuck for hours and it turns out to be silly..
thanks a lot Marijan, fixed it, it worked! :)

**Comment by marijanbeg** [comment]
Great, thank you for letting us know. I will close this issue now.

Please do not hesitate to let us know if there is anything else we can help with.
