### ISSUE TITLE
Issue with accessing jupyterhub

### ISSUE THREAD

**Issue by edsml-cc2823** [ese-msc/introduction-to-python#76]
Hello Marijian,
I tried to access the exercises using jupyterhub today, but it raises a 403 error and says that I am currently not authorised to use the hub and to contact the hub administrator. May I know how to fix this error?

Charis

**Comment by edsml-cc2823** [comment]
I was able to access it for quite a few times last week, not sure why this happened today

**Comment by marijanbeg** [comment]
Thank you for the clarification. I did a few tests, and it seems JupyterHub is running. Could you try to access it again?

**Comment by marijanbeg** [comment]
Have you maybe changed your GitHub username?

**Comment by edsml-cc2823** [comment]
Yes, I changed my username as james sent an email about updating the username to correspond to the imperial one. How did it affect and should I change it back?

**Comment by marijanbeg** [comment]
Hi @edsml-cc2823, we added new usernames to the list of allowed ones. Could you please try if you can access JupyterHub now?

**Comment by edsml-cc2823** [comment]
Hi marijian,
It works now, thank you!
