### ISSUE TITLE
LineSegment intersection assertion error

### ISSUE THREAD

**Issue by esemsc-bg721** [ese-msc/introduction-to-python#88]
Hi there,
Apologies if this has already been asked, but I am unclear on how we are meant to interpret if colinear line segments can intersect. We are given the following assertions in lecture 5: 

line_segment1 = LineSegment(Point(0, 0), Point(10, 10))
line_segment2 = LineSegment(Point(1, 1), Point(11, 11))

assert not line_segment1.intersects(line_segment2)

I have modified my LineSegment class to consider the colinear case, and as far as I understand it, these line segments do in fact intersect infinitely many times between (1, 1) and (10, 10). However, the assertion disagrees. Am I misunderstanding something? Here is the code to my LineSegment class:
class LineSegment:
    def __init__(self, start: Point, end: Point):
        # Write appropriate code here to store the start and end points
        self.start = start
        self.end = end

    def __repr__(self):
        return f"LineSegment({self.start}, {self.end})"

    def length(self) -> float:
        # Write appropriate code here, updating the class to
        # return the length of the line segment
        return np.linalg.norm((self.end.x - self.start.x, self.end.y - self.start.y))

    def midpoint(self) -> Point:
        x_mid = (self.start.x + self.end.x) / 2
        y_mid = (self.start.y + self.end.y) / 2
        return Point(x_mid, y_mid)

    def contains(self, point: Point) -> bool:
        try:
            t = (point.x - self.start.x) / (self.end.x - self.start.x)
            assert t == (point.y - self.start.y) / (self.end.y - self.start.y)
            return 0 <= t <= 1
        except AssertionError:
            return False

    def intersects(self, other) -> bool:
        try:
            A = np.matrix([[self.end.x - self.start.x, other.start.x - other.end.x], 
                           [self.end.y - self.start.y, other.start.y - other.end.y]])
            b = np.array([[other.start.x - self.start.x], [other.start.y - self.start.y]])
            t = A.I @ b
            return 0 <= t[0][0] <= 1 and 0 <= t[1][0] <= 1
            
        except np.linalg.LinAlgError:
            # check for colinearity
            
            points = [self.start, self.end, other.start, other.end]
            points_x = [i.x for i in points]
            point_x_max_index = points_x.index(max(points_x))
            point_x_min_index = points_x.index(min(points_x))
            big_line_segment = LineSegment(points[point_x_min_index], points[point_x_max_index])
            points.remove(points[point_x_max_index])
            points.remove(points[point_x_min_index])

            return big_line_segment.contains(points[0])
All the best,
Ben

**Comment by marijanbeg** [comment]
Hi Ben, thank you for your question. For simplicity, we assumed the line segments are not colinear, as explained in the lecture: `You can assume that the line segments are not colinear [...]`. Our tests reflect that.

If you have considered a colinear case, then this is definitely a plus. :)
