### ISSUE TITLE
Potential error with algorithm used to check if a point is inside a triangle. 

### ISSUE THREAD

**Issue by esemsc-bg721** [ese-msc/introduction-to-python#89]
Hi there,
I believe there is an error with the algorithm you have given us to determine if a point is within a triangle in lecture 5, more specifically with how the normal vector is calculated. If we use (the latex is not rendering correctly, the below should be a 2x1 vector)

$$\mathbf{n} = \begin{pmatrix} y_2 - y_1 \\ x_1 - x_2 \end{pmatrix},$$ 

we end up with normal vectors that face outside of the triangle. This means that if a point is inside the triangle, the dot product between this normal and the vector from one of the vertices of the edge to the point will be negative as the angle will be greater than 90 degrees. I think we are either meant to compute the normal vector using 

$$\mathbf{n} = \begin{pmatrix} y_1 - y_2 \\ x_2 - x_1 \end{pmatrix}$$ 

and then proceed as stated, or we should take a negative dot product for each edge as a sign that the point is inside the triangle. Please do let me know if I am wrong.

All the best,
Ben

**Comment by marijanbeg** [comment]
Hi @esemsc-fe7bf37d, thank you for spotting this. Yes, you can either change the way you calculate the normal vector or use the negative of the dot product.

We will consider your suggestion and attempt to introduce this change for next year.
