### ISSUE TITLE
Comparing LineSegment to a real number - Lecture 5 (The Triangle Class Implementation)

### ISSUE THREAD

**Issue by esemsc-ss2524** [ese-msc/introduction-to-python#90]
Hello there,
I believe there is a logical bug in the test cell of **The Triangle class Implementation**:
![image](https://github.com/user-attachments/assets/c050ee78-f59d-4881-b48a-15888e9678d0)

A closer look at the assertions hints that it was intended to check against the **length** of the line segment.
Best regards,
Simranjeet

**Comment by marijanbeg** [comment]
Hi @esemsc-d888db94, thank you for your message. What is the value of `t.edges()` you compute?

**Comment by esemsc-ss2524** [comment]
Thank you for your response @marijanbeg !
As was given in the specification, t.edges() returns a `tuple` containing the three `LineSegment`s:
![image](https://github.com/user-attachments/assets/1d21a2e5-c41c-4c36-85ef-f63e6d35509a)

**Comment by marijanbeg** [comment]
Hi @esemsc-d888db94, thank you for the clarification. I meant, what is the value you are calculating?

If you draw a triangle with those points, you will see that the edge lengths should be 1, 1, and sqrt(2). The tests are testing for that.

**Comment by esemsc-ss2524** [comment]
> Hi @esemsc-d888db94, thank you for the clarification. I meant, what is the value you are calculating?
> 
> If you draw a triangle with those points, you will see that the edge lengths should be 1, 1, and sqrt(2). The tests are testing for that.

Hi @marijanbeg ,
The image I pasted above is indeed what I calculate.
`t.edges()[0]` is `LineSegment(Point(x=0, y=0), Point(x=1, y=0))`
and not any numeric value. 

But now I see that it expects us to return the **lengths** of the `LineSegment`s instead of the objects. From the instructions I was rather convinced that it was the latter. 

I will change the code to return the lengths.
Thank you for the help!
Best,
Simranjeet

**Comment by marijanbeg** [comment]
Thank you for the update. I will close the issue now.
