### ISSUE TITLE
Typo in the palindromes section of lecture 6 

### ISSUE THREAD

**Issue by esemsc-gh124** [ese-msc/introduction-to-python#92]
Dear Dr Beg,

There is possibly a typo in the examples of the `is_palindrome()` function in Lecture 6.

The description of the function writes:

> ... and it should ignore spaces, so that the phrase "nurses run" is also considered a palindrome.

However, in the examples string, one example is:

> \>\>\> test = 'nurse run'
> \>\>\> is_palindrome(test)
>   True
> \>\>\> test = 'nurse run'

We should either add the missing `'s'` to the two `'nurse run'`s, or change the `True` to `False`.

Thank you for your time in advance.

Yours truly,
esemsc-df329480 (Guanyuming He)

**Comment by marijanbeg** [comment]
Hi @esemsc-df329480 , thank you for spotting that. Yes, this is a mistake. The `assert` statement should be:

```python
>>> test = 'nurses run'
>>> is_palindrome(test)
True
```

I will close this issue and label it to ensure this is fixed for the next cohort.
