### ISSUE TITLE
Regarding the submission of the exercises

### ISSUE THREAD

**Issue by esemsc-gh124** [ese-msc/introduction-to-python#93]
Dear Dr Beg,

The pre-sessional material says that we should have received something about the submission of these exercises yesterday, but I have found none in my email inbox about it, nor did I remember that it was mentioned in the past two days of the induction week.

> We will ask you to submit some your Python exercise work onto GitHub in October, at the end of the course induction week. You will be provided with a new GitHub repository to upload to at the beginning of the week. You will receive more details regarding submission at the beginning of induction week on the 30th September.

I am worried about this, since its due day, 4 Oct, is approaching fast. I don't know who I should email about this, so I am opening an issue here.

Thank you for your reply in advance.

Yours truly,
acse-guany (Guanyuming He)

**Comment by marijanbeg** [comment]
Hi @acse-guany, thank you for your question. You should soon get instructions from module coordinators.

Please note that you will also be asked to change your GitHub username.

**Comment by marijanbeg** [comment]
Hi @acse-guany, I have investigated, and it looks like the instructions on how to submit were sent yesterday. Please check your inbox.

**Comment by acse-gh00** [comment]
Dear Dr Beg,

That is really strange. I checked my inbox (deleted items and junk)  before opening this issue, and have just checked again now. There's no mentioning of how to submit these exercises, as you can see in the following screenshots.

![image](https://github.com/user-attachments/assets/4de587b6-6daa-4847-adf9-0876283e8361)![image](https://github.com/user-attachments/assets/eb3adcd8-7039-4e21-b54f-51eca5669d7a)![image](https://github.com/user-attachments/assets/463baf70-a01e-4130-ac1d-d07ed13f910f)

There was indeed an email message about laptop setup in which the GitHub username change was mentioned. It did say that GitHub will be used for submitting assignments, but it didn't say anything about these exercises.
![image](https://github.com/user-attachments/assets/1701ce34-f262-4c6a-8a7e-0f83cf5ab1a2)

**Comment by marijanbeg** [comment]
Hi @acse-gh00, thank you for letting us know. There should now be instructions on the General channel on Teams as well. For any further questions on how to submit pre-sessional notebooks, please reply to that post.

Can I ask you to please delete your last comment? This repository is public, and we do not want any personal information, such as the screenshot of your inbox, to be here.

Thank you!

**Comment by esemsc-gh124** [comment]
Dear Dr Beg,

I am sorry. I didn't realise that the screenshots could be sensitive. I have now deleted the last comment.

**Comment by marijanbeg** [comment]
Thank you!
